<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Form\Type\UserRegistrationType' shared autowired service.

return $this->services['AppBundle\\Form\\Type\\UserRegistrationType'] = new \AppBundle\Form\Type\UserRegistrationType();
