<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['AppBundle\\Controller\\CommentController:commentAction' => function () {
    return ${($_ = isset($this->services['service_locator..lu7gd0']) ? $this->services['service_locator..lu7gd0'] : $this->load('getServiceLocator__Lu7gd0Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ContactController:contactAction' => function () {
    return ${($_ = isset($this->services['service_locator.ffywtj_']) ? $this->services['service_locator.ffywtj_'] : $this->load('getServiceLocator_FfywtjService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ContactController:processAction' => function () {
    return ${($_ = isset($this->services['service_locator.ouf36xr']) ? $this->services['service_locator.ouf36xr'] : $this->load('getServiceLocator_Ouf36xrService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\PostController:postAction' => function () {
    return ${($_ = isset($this->services['service_locator.4px8aif']) ? $this->services['service_locator.4px8aif'] : $this->load('getServiceLocator_4px8aifService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:loginAction' => function () {
    return ${($_ = isset($this->services['service_locator.bevcbmb']) ? $this->services['service_locator.bevcbmb'] : $this->load('getServiceLocator_BevcbmbService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.wp6o_h8']) ? $this->services['service_locator.wp6o_h8'] : $this->load('getServiceLocator_Wp6oH8Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:updatePasswordAction' => function () {
    return ${($_ = isset($this->services['service_locator.n.avb1g']) ? $this->services['service_locator.n.avb1g'] : $this->load('getServiceLocator_N_Avb1gService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\CommentController::commentAction' => function () {
    return ${($_ = isset($this->services['service_locator..lu7gd0']) ? $this->services['service_locator..lu7gd0'] : $this->load('getServiceLocator__Lu7gd0Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ContactController::contactAction' => function () {
    return ${($_ = isset($this->services['service_locator.ffywtj_']) ? $this->services['service_locator.ffywtj_'] : $this->load('getServiceLocator_FfywtjService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ContactController::processAction' => function () {
    return ${($_ = isset($this->services['service_locator.ouf36xr']) ? $this->services['service_locator.ouf36xr'] : $this->load('getServiceLocator_Ouf36xrService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\PostController::postAction' => function () {
    return ${($_ = isset($this->services['service_locator.4px8aif']) ? $this->services['service_locator.4px8aif'] : $this->load('getServiceLocator_4px8aifService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::loginAction' => function () {
    return ${($_ = isset($this->services['service_locator.bevcbmb']) ? $this->services['service_locator.bevcbmb'] : $this->load('getServiceLocator_BevcbmbService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.wp6o_h8']) ? $this->services['service_locator.wp6o_h8'] : $this->load('getServiceLocator_Wp6oH8Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::updatePasswordAction' => function () {
    return ${($_ = isset($this->services['service_locator.n.avb1g']) ? $this->services['service_locator.n.avb1g'] : $this->load('getServiceLocator_N_Avb1gService.php')) && false ?: '_'};
}]));
