<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Form\Type\ContactType' shared autowired service.

return $this->services['AppBundle\\Form\\Type\\ContactType'] = new \AppBundle\Form\Type\ContactType();
