<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGmyuito\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGmyuito/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGmyuito.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGmyuito\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerGmyuito\appTestDebugProjectContainer([
    'container.build_hash' => 'Gmyuito',
    'container.build_id' => 'c08fdf3d',
    'container.build_time' => 1601382725,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGmyuito');
