<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1mocs6o\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1mocs6o/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1mocs6o.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1mocs6o\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container1mocs6o\appDevDebugProjectContainer([
    'container.build_hash' => '1mocs6o',
    'container.build_id' => '283044ce',
    'container.build_time' => 1601384983,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1mocs6o');
